name: Download (Both Sides)
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
    download:
        strategy:
            matrix:
                os: [macos-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              
            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                distribution: temurin
                java-version: 21
              
            - name: Download
              run: java -jar packwiz-installer-bootstrap.jar -g -s both pack.toml
              
            - name: Capture downloaded jars
              uses: actions/upload-artifact@v4
              with:
                  name: mods
                  path: |
                    ./mods
                    !**/*.toml
