name: Export
on:
  workflow_dispatch:
  release:

jobs:
    export:
        strategy:
            matrix:
                os: [macos-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              
            - name: Make Executable
              run: chmod +x ./packwiz
              
            - name: Export to `.mrpack`
              run: ./packwiz mr export
              
            - name: Capture Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: Pack (Modrinth)
                  path: ./**.mrpack
